oksign:
  api-key: <devine>
  base-url: https://www.oksign.be/services/rest/v1/
  webhook-secret: your-oksign-webhook-secret

server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  application:
    name: oksign-itsme-backend
