oksign:
  api-key: 118165;181921-C3703678-91AE-8916-F822-A5F0B97E8434;dev-test-itsme-backend
  base-url: https://www.oksign.be/services/rest/v1/
  webhook-secret: your-oksign-webhook-secret

server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  application:
    name: oksign-itsme-backend